#
# pacman.aarch64.conf
#
[options]
Architecture = aarch64
ParallelDownloads = 25
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = http://mirror.archlinuxarm.org/aarch64/$repo

[extra]
Server = http://mirror.archlinuxarm.org/aarch64/$repo

[community]
Server = http://mirror.archlinuxarm.org/aarch64/$repo

[alarm]
Server = http://mirror.archlinuxarm.org/aarch64/$repo

[aur]
Server = http://mirror.archlinuxarm.org/aarch64/$repo

[acreetionOSREPO-main]
SigLevel = Optional
Server = https://iso.acreetionos.org:8448/repo-main/aarch64
