#
# pacman.armv7h.conf
#
[options]
Architecture = armv7h
ParallelDownloads = 25
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = http://mirror.archlinuxarm.org/armv7h/$repo

[extra]
Server = http://mirror.archlinuxarm.org/armv7h/$repo

[community]
Server = http://mirror.archlinuxarm.org/armv7h/$repo

[alarm]
Server = http://mirror.archlinuxarm.org/armv7h/$repo

[aur]
Server = http://mirror.archlinuxarm.org/armv7h/$repo

[acreetionOSREPO-main]
SigLevel = Optional
Server = https://iso.acreetionos.org:8448/repo-main/armv7h
