#
# pacman.riscv64.conf
#
[options]
Architecture = riscv64
ParallelDownloads = 25
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://mirror.iscas.ac.cn/archriscv/$repo/os/$arch

[extra]
Server = https://mirror.iscas.ac.cn/archriscv/$repo/os/$arch

[acreetionOSREPO-main]
SigLevel = Optional
Server = https://iso.acreetionos.org:8448/repo-main/riscv64
