[greeter]
background=/usr/share/backgrounds/acreetion.png
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=Sans 10
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
keyboard=onboard
position=50% 50%
